name: Cookie Project BE Deploy

on:
  push:
   branches:
      - develop
  pull_request:
      branches:
        - develop
      types:
        - closed

# 워크플로우가 깃 레포에 대한 권한을 읽기만 가능하게 설정
permissions:
  contents: read

# 작업 시작
jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle Wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew build

      # 5. EC2 서버로 배포
      - name: Deploy to EC2
        run: |
          set -e  # 에러 발생 시 중단
          echo "빌드 배포에 실패 했습니다."
          
          # 비공개 키 파일 생성
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          # 프로젝트 경로 설정
          PROJECT_DIR="/home/ubuntu/Cookie-BE/cookie"
          BUILD_DIR="$PROJECT_DIR/build/libs"
          DEPLOY_JAR="cookie-0.0.1-SNAPSHOT.jar"
          
          # 빌드된 JAR 파일을 EC2로 전송
          echo "EC2에 Jar 파일 전송 시작"
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/$DEPLOY_JAR ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:$BUILD_DIR/
          
          # EC2에서 실행 중인 애플리케이션 중지 및 새로운 JAR 파일 실행
          echo "EC2 내부에서 Jar 파일 실행"
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << EOF
          echo "실행 중인 현재 서버 종료..."
          pkill -f 'java -jar' || true
          echo "서버 재시동 중...!!."
          nohup java -jar $BUILD_DIR/$DEPLOY_JAR > $BUILD_DIR/app.log 2>&1 &
          EOF
          
          echo "✅ EC2 서버에 배포 완료!"
          # 비공개 키 파일 삭제
          rm -f private_key.pem
